### ISSUE TITLE
Create Mocks for Pages

### ISSUE THREAD

**Issue by JaidenSy** [AJbudget/BudgetApp#2]
create mocks for front end pages to better understand the end-to-end user experience

**Comment by JaidenSy** [comment]
![image](https://github.com/AJbudget/BudgetApp/assets/96254931/03b3d7e6-eb69-4cd9-9546-f6e8c991aa09)

Created Page for MainPage

**Comment by JaidenSy** [comment]
![image](https://github.com/AJbudget/BudgetApp/assets/96254931/fa71f5fd-c682-48c0-a0f6-6b4e2eaa5c96)

Incomes Page instead of 'Budgets'

**Comment by JaidenSy** [comment]
Added Spending Page to track user spending based on category

![image](https://github.com/AJbudget/BudgetApp/assets/96254931/d0787775-0981-4240-8964-19f56220899d)

**Comment by huangelina** [comment]
Added Category Page to track category spending for user
![image](https://github.com/AJbudget/BudgetApp/assets/137594730/e7ce246d-c247-40cc-8200-fa66a8d4740d)

**Comment by JaidenSy** [comment]
added page for
